version: "3.1"

services:
  go-server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.0-alpine3.14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
